[2022-01-28 09:40:28,024: INFO: stage_01_prepare]: 
********************
[2022-01-28 09:40:28,024: INFO: stage_01_prepare]: >>>>> stage One started <<<<<
[2022-01-28 09:40:28,031: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-01-28 09:40:28,032: INFO: common]: yaml file: params.yaml loaded successfully
[2022-01-28 09:40:28,033: INFO: stage_01_prepare]: >>>>> stage One completed!<<<<<

[2022-01-28 12:35:52,459: INFO: stage_01_prepare]: 
********************
[2022-01-28 12:35:52,459: INFO: stage_01_prepare]: >>>>> stage One started <<<<<
[2022-01-28 12:35:52,466: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-01-28 12:35:52,484: INFO: common]: yaml file: params.yaml loaded successfully
[2022-01-28 12:35:52,484: ERROR: stage_01_prepare]: 'PREPARED_DATA'
Traceback (most recent call last):
  File "src/stage_01_prepare.py", line 48, in <module>
    main(config_path=parsed_args.config, params_path=parsed_args.params)
  File "src/stage_01_prepare.py", line 34, in main
    prepared_data_dir_path = os.path.join(artifacts['ARTIFACTS_DIR'], artifacts['PREPARED_DATA'])
KeyError: 'PREPARED_DATA'
[2022-01-28 12:36:10,213: INFO: stage_01_prepare]: 
********************
[2022-01-28 12:36:10,213: INFO: stage_01_prepare]: >>>>> stage One started <<<<<
[2022-01-28 12:36:10,233: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-01-28 12:36:10,236: INFO: common]: yaml file: params.yaml loaded successfully
[2022-01-28 12:36:10,237: INFO: common]: created directory at: artifacts\prepared
[2022-01-28 12:36:10,237: INFO: stage_01_prepare]: >>>>> stage One completed!<<<<<

